language: haskell

before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh

script:
  - cabal configure
  - cabal build

install:
  - cabal sandbox init
  - cabal install --only-dependencies

after_script:
  - cd example/CommandAPI
  - cabal sandbox init
  - cabal sandbox add-source ../../
  - cabal install --only-dependencies
  - cabal build